server:
  port: 8082
spring:
  application:
    name: service-hi
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/