server:
  port: 8010
spring:
  application:
    name: service-ribbon
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  sleuth:
    sampler:
      percentage: 1.0
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/